const DEFAULT_EVENTS = [
  {
    id: "sunset-5k",
    name: "Sunset 5K Campus Run",
    nameZh: "校园日落5K跑",
    timeLabel: "18:30 - Thu",
    timeLabelZh: "18:30 - 周四",
    timeOfDay: "evening",
    location: "Dushu Lake Gate A",
    locationZh: "独墅湖A口",
    distance: 5,
    level: "Beginner",
    pace: "6'30\"-7'30\" / km",
    capacity: 36,
    spotsLeft: 12,
    tags: ["Beginner Friendly", "Social", "Campus"],
    tagsZh: ["新手友好", "社交", "校园"],
    gear: ["Water bottle", "Reflective vest", "Comfort shoes"],
    gearZh: ["水瓶", "反光背心", "舒适跑鞋"],
    description:
      "A welcoming lakeside loop with a guided warm-up and friendly pacing. Designed for first-time group runners who want to feel supported.",
    descriptionZh: "环湖日落轻松跑，包含热身与配速引导，欢迎首次参与者。",
    rewards: "Earn 50 pts + 'First Finish' badge",
    rewardsZh: "获得50积分 + '首跑完成'徽章",
    lat: 31.264,
    lng: 120.739,
    routeCoords: [
      [31.264, 120.739],
      [31.262, 120.744],
      [31.268, 120.746],
      [31.27, 120.739],
      [31.266, 120.732],
      [31.264, 120.739],
    ],
    route: [
      { name: "Gate A Start", type: "start" },
      { name: "Hydration Point", type: "water" },
      { name: "Sunset Photo Spot", type: "photo" },
      { name: "Motivation Arch", type: "checkpoint" },
      { name: "Finish & Stretch", type: "finish" },
    ],
    routeZh: [
      { name: "独墅湖A口起点", type: "start" },
      { name: "补水点", type: "water" },
      { name: "日落拍照点", type: "photo" },
      { name: "鼓励拱门", type: "checkpoint" },
      { name: "终点拉伸区", type: "finish" },
    ],
  },
  {
    id: "night-jog",
    name: "Beginner Night Jog",
    nameZh: "新手夜跑",
    timeLabel: "19:15 - Fri",
    timeLabelZh: "19:15 - 周五",
    timeOfDay: "evening",
    location: "Moonlight Track Field",
    locationZh: "月光田径场",
    distance: 3.5,
    level: "Beginner",
    pace: "7'00\"-8'00\" / km",
    capacity: 24,
    spotsLeft: 8,
    tags: ["Night Run", "Stress Relief"],
    tagsZh: ["夜跑", "减压"],
    gear: ["Head lamp", "Light jacket"],
    gearZh: ["头灯", "薄外套"],
    description:
      "Soft lighting, calm pace, and an easy loop around the field. Perfect for de-stress after a long day.",
    descriptionZh: "低强度夜跑，舒缓节奏，适合放松。",
    rewards: "Earn 40 pts + 'Night Owl' badge",
    rewardsZh: "获得40积分 + '夜跑达人'徽章",
    lat: 31.301,
    lng: 120.62,
    routeCoords: [
      [31.301, 120.62],
      [31.302, 120.623],
      [31.303, 120.621],
      [31.301, 120.618],
      [31.301, 120.62],
    ],
    route: [
      { name: "Warm-up Zone", type: "start" },
      { name: "Breathing Corner", type: "checkpoint" },
      { name: "Glow Station", type: "photo" },
      { name: "Finish Circle", type: "finish" },
    ],
    routeZh: [
      { name: "热身区", type: "start" },
      { name: "呼吸角", type: "checkpoint" },
      { name: "荧光打卡点", type: "photo" },
      { name: "终点圈", type: "finish" },
    ],
  },
  {
    id: "team-challenge",
    name: "Team Challenge Run",
    nameZh: "团队挑战跑",
    timeLabel: "08:00 - Sat",
    timeLabelZh: "08:00 - 周六",
    timeOfDay: "morning",
    location: "Industrial Park Greenway",
    locationZh: "园区绿道",
    distance: 8,
    level: "Intermediate",
    pace: "5'30\"-6'30\" / km",
    capacity: 40,
    spotsLeft: 14,
    tags: ["Team", "Challenge", "Greenway"],
    tagsZh: ["团队", "挑战", "绿道"],
    gear: ["Energy gel", "Cap"],
    gearZh: ["能量胶", "帽子"],
    description:
      "Group-based run with mini challenges at checkpoints. Meet new buddies and finish together.",
    descriptionZh: "团队协作与小挑战结合，结伴完成。",
    rewards: "Earn 70 pts + 'Team Spirit' badge",
    rewardsZh: "获得70积分 + '团队精神'徽章",
    lat: 31.315,
    lng: 120.7,
    routeCoords: [
      [31.315, 120.7],
      [31.318, 120.703],
      [31.319, 120.695],
      [31.314, 120.692],
      [31.315, 120.7],
    ],
    route: [
      { name: "Greenway Gate", type: "start" },
      { name: "Bridge Sprint", type: "checkpoint" },
      { name: "Water Stop", type: "water" },
      { name: "Finish Plaza", type: "finish" },
    ],
    routeZh: [
      { name: "绿道入口", type: "start" },
      { name: "桥上冲刺", type: "checkpoint" },
      { name: "补水点", type: "water" },
      { name: "终点广场", type: "finish" },
    ],
  },
  {
    id: "tempo-club",
    name: "Tempo Club 10K",
    nameZh: "节奏训练10K",
    timeLabel: "07:30 - Sun",
    timeLabelZh: "07:30 - 周日",
    timeOfDay: "morning",
    location: "East Gate Stadium",
    locationZh: "东门体育场",
    distance: 10,
    level: "Advanced",
    pace: "4'30\"-5'30\" / km",
    capacity: 28,
    spotsLeft: 6,
    tags: ["Tempo", "Performance"],
    tagsZh: ["节奏", "训练"],
    gear: ["Watch", "Hydration pack"],
    gearZh: ["运动手表", "水袋"],
    description:
      "A structured tempo session with pacer leaders. Push your pace while staying safe.",
    descriptionZh: "节奏跑课程，配速员领跑，安全提升。",
    rewards: "Earn 90 pts + 'Tempo Master' badge",
    rewardsZh: "获得90积分 + '节奏大师'徽章",
    lat: 31.305,
    lng: 120.68,
    routeCoords: [
      [31.305, 120.68],
      [31.307, 120.683],
      [31.308, 120.678],
      [31.304, 120.675],
      [31.305, 120.68],
    ],
    route: [
      { name: "Track Start", type: "start" },
      { name: "Speed Gate", type: "checkpoint" },
      { name: "Recovery Spot", type: "water" },
      { name: "Finish Line", type: "finish" },
    ],
    routeZh: [
      { name: "跑道起点", type: "start" },
      { name: "速度门", type: "checkpoint" },
      { name: "恢复点", type: "water" },
      { name: "终点线", type: "finish" },
    ],
  },
  {
    id: "heritage-loop",
    name: "Heritage Loop Story Run",
    nameZh: "古城故事跑",
    timeLabel: "16:00 - Sun",
    timeLabelZh: "16:00 - 周日",
    timeOfDay: "afternoon",
    location: "Old Town Canal",
    locationZh: "老城运河",
    distance: 6,
    level: "Intermediate",
    pace: "6'00\"-7'00\" / km",
    capacity: 32,
    spotsLeft: 10,
    tags: ["Storytelling", "Culture", "Photo"],
    tagsZh: ["故事", "文化", "拍照"],
    gear: ["Phone camera", "Comfort shoes"],
    gearZh: ["手机相机", "舒适跑鞋"],
    description:
      "A culture-forward run with story prompts and photo checkpoints along the canal.",
    descriptionZh: "沿运河的文化路线，包含故事提示和拍照点。",
    rewards: "Earn 65 pts + 'Memory Keeper' badge",
    rewardsZh: "获得65积分 + '记忆收藏家'徽章",
    lat: 31.312,
    lng: 120.62,
    routeCoords: [
      [31.312, 120.62],
      [31.314, 120.624],
      [31.316, 120.621],
      [31.312, 120.616],
      [31.312, 120.62],
    ],
    route: [
      { name: "Canal Gate", type: "start" },
      { name: "Story Stop", type: "checkpoint" },
      { name: "Photo Dock", type: "photo" },
      { name: "Finish Bridge", type: "finish" },
    ],
    routeZh: [
      { name: "运河起点", type: "start" },
      { name: "故事站", type: "checkpoint" },
      { name: "摄影码头", type: "photo" },
      { name: "终点桥", type: "finish" },
    ],
  },
  {
    id: "recovery-run",
    name: "Recovery Social Shuffle",
    nameZh: "恢复社交慢跑",
    timeLabel: "17:00 - Wed",
    timeLabelZh: "17:00 - 周三",
    timeOfDay: "afternoon",
    location: "Community Fitness Deck",
    locationZh: "社区健身平台",
    distance: 4.2,
    level: "Beginner",
    pace: "7'30\"-8'30\" / km",
    capacity: 22,
    spotsLeft: 5,
    tags: ["Recovery", "Chatty", "Inclusive"],
    tagsZh: ["恢复", "聊天", "包容"],
    gear: ["Stretch band", "Water"],
    gearZh: ["拉伸带", "饮水"],
    description:
      "Low-pressure social jog with mini mobility breaks and buddy pairing.",
    descriptionZh: "低压力社交慢跑，穿插拉伸。",
    rewards: "Earn 45 pts + 'Supportive Runner' badge",
    rewardsZh: "获得45积分 + '陪伴跑者'徽章",
    lat: 31.29,
    lng: 120.615,
    routeCoords: [
      [31.29, 120.615],
      [31.292, 120.618],
      [31.293, 120.612],
      [31.289, 120.61],
      [31.29, 120.615],
    ],
    route: [
      { name: "Deck Start", type: "start" },
      { name: "Mobility Stop", type: "checkpoint" },
      { name: "Hydration Station", type: "water" },
      { name: "Finish Lounge", type: "finish" },
    ],
    routeZh: [
      { name: "平台起点", type: "start" },
      { name: "拉伸点", type: "checkpoint" },
      { name: "补水站", type: "water" },
      { name: "终点休息区", type: "finish" },
    ],
  },
];

const DEFAULT_BADGES = [
  { id: "first-finish", name: "First Finish", nameZh: "首跑完成", hint: "Join your first run", hintZh: "完成你的第一次活动" },
  {
    id: "route-explorer",
    name: "Route Explorer",
    nameZh: "路线探索",
    hint: "Complete all checkpoints",
    hintZh: "完成所有打卡点",
  },
  { id: "team-spirit", name: "Team Spirit", nameZh: "团队精神", hint: "Join a team run", hintZh: "参加团队活动" },
  { id: "momentum", name: "Momentum", nameZh: "连续打卡", hint: "3 runs streak", hintZh: "连续参加3次" },
  { id: "night-owl", name: "Night Owl", nameZh: "夜跑达人", hint: "Complete a night run", hintZh: "完成夜跑活动" },
  { id: "city-explorer", name: "City Explorer", nameZh: "城市探索", hint: "Check in onsite", hintZh: "完成一次现场签到" },
];

const CITY_SPOTS = [
  {
    id: "dushu_lake",
    name: "Dushu Lake",
    nameZh: "独墅湖",
    description: "Lakeside breeze, sunset reflections, easy loops for new runners.",
    descriptionZh: "湖畔微风与日落倒影，新手友好环湖路线。",
    lat: 31.264,
    lng: 120.739,
    vibe: "Campus Lakeside",
    vibeZh: "校园湖畔",
  },
  {
    id: "jinji_lake",
    name: "Jinji Lake",
    nameZh: "金鸡湖",
    description: "Wide paths and city skyline views for social group runs.",
    descriptionZh: "宽阔步道与城市天际线，适合社交跑。",
    lat: 31.311,
    lng: 120.682,
    vibe: "City Skyline",
    vibeZh: "城市天际线",
  },
  {
    id: "pingjiang_road",
    name: "Pingjiang Road",
    nameZh: "平江路",
    description: "Historic alleys with photo checkpoints and story prompts.",
    descriptionZh: "历史街巷与拍照打卡点，适合故事主题跑。",
    lat: 31.312,
    lng: 120.625,
    vibe: "Heritage Story",
    vibeZh: "文化故事",
  },
  {
    id: "humble_garden",
    name: "Humble Administrator's Garden",
    nameZh: "拙政园",
    description: "Calm green zone nearby for gentle recovery jogs.",
    descriptionZh: "园林绿意，适合恢复跑与舒缓节奏。",
    lat: 31.324,
    lng: 120.627,
    vibe: "Garden Calm",
    vibeZh: "园林静谧",
  },
  {
    id: "tiger_hill",
    name: "Tiger Hill",
    nameZh: "虎丘",
    description: "Rolling slopes that add a playful climbing challenge.",
    descriptionZh: "起伏坡度带来有趣的挑战节奏。",
    lat: 31.34,
    lng: 120.587,
    vibe: "Hill Challenge",
    vibeZh: "坡度挑战",
  },
  {
    id: "suzhou_museum",
    name: "Suzhou Museum",
    nameZh: "苏州博物馆",
    description: "A quiet cultural loop for reflective, mindful runs.",
    descriptionZh: "安静文化路线，适合沉浸式慢跑。",
    lat: 31.324,
    lng: 120.626,
    vibe: "Culture Loop",
    vibeZh: "文化环线",
  },
  {
    id: "shantang_street",
    name: "Shantang Street",
    nameZh: "山塘街",
    description: "Night lights, snack stops, and plenty of photo moments.",
    descriptionZh: "夜景灯光与美食补给，适合夜跑打卡。",
    lat: 31.334,
    lng: 120.59,
    vibe: "Night Market",
    vibeZh: "夜市氛围",
  },
];
